// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Payment struct {
	ID              interface{}
	CreatedOn       time.Time
	UpdatedAt       time.Time
	UserID          interface{}
	RoomID          interface{}
	ItemDescription sql.NullString
	Amount          float64
}

type PaymentRoom struct {
	ID          interface{}
	CreatedOn   time.Time
	UpdatedAt   time.Time
	CreatedBy   interface{}
	RawJsonData sql.NullString
}

type User struct {
	ID        interface{}
	CreatedOn time.Time
	UpdatedAt time.Time
	Username  string
	Balance   sql.NullInt64
}
