// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payment_room.sql

package database

import (
	"context"
	"database/sql"
)

const createPaymentRoom = `-- name: CreatePaymentRoom :one
INSERT INTO payment_rooms(id, created_on, updated_at, created_by, raw_json_data)
VALUES(?, DATETIME('now','localtime'), DATETIME('now','localtime'), ?, ?) RETURNING id, created_on, updated_at, created_by, raw_json_data
`

type CreatePaymentRoomParams struct {
	ID          interface{}
	CreatedBy   interface{}
	RawJsonData sql.NullString
}

func (q *Queries) CreatePaymentRoom(ctx context.Context, arg CreatePaymentRoomParams) (PaymentRoom, error) {
	row := q.db.QueryRowContext(ctx, createPaymentRoom, arg.ID, arg.CreatedBy, arg.RawJsonData)
	var i PaymentRoom
	err := row.Scan(
		&i.ID,
		&i.CreatedOn,
		&i.UpdatedAt,
		&i.CreatedBy,
		&i.RawJsonData,
	)
	return i, err
}
