// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(id, created_on, updated_at, username, balance)
VALUES (?, DATETIME('now', 'localtime'), DATETIME('now','localtime'), ?, 50000.0) RETURNING id, created_on, updated_at, username, balance
`

type CreateUserParams struct {
	ID       interface{}
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedOn,
		&i.UpdatedAt,
		&i.Username,
		&i.Balance,
	)
	return i, err
}
